// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8bymnTCcgHKPbUSgvvU383LKv8ddo3X8',
    appId: '1:215566645667:web:9f17d77864a3d446720216',
    messagingSenderId: '215566645667',
    projectId: 'primekeyfinance-c95bc',
    authDomain: 'primekeyfinance-c95bc.firebaseapp.com',
    storageBucket: 'primekeyfinance-c95bc.firebasestorage.app',
    measurementId: 'G-BB8YWPFX55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQwsVs2L9gQ6zorzXxDQY6WHB27PA4ok',
    appId: '1:215566645667:android:033e10ae8b689ffc720216',
    messagingSenderId: '215566645667',
    projectId: 'primekeyfinance-c95bc',
    storageBucket: 'primekeyfinance-c95bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVugXNWuDQiLH_UCoFyrwchANrLX17luc',
    appId: '1:309325071712:ios:f32b38b8f39a26c6ec2a80',
    messagingSenderId: '309325071712',
    projectId: 'primekeyfinance-474f2',
    storageBucket: 'primekeyfinance-474f2.firebasestorage.app',
    iosBundleId: 'com.example.primekeyloan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVugXNWuDQiLH_UCoFyrwchANrLX17luc',
    appId: '1:309325071712:ios:f32b38b8f39a26c6ec2a80',
    messagingSenderId: '309325071712',
    projectId: 'primekeyfinance-474f2',
    storageBucket: 'primekeyfinance-474f2.firebasestorage.app',
    iosBundleId: 'com.example.primekeyloan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVugXNWuDQiLH_UCoFyrwchANrLX17luc',
    appId: '1:309325071712:web:51ea345bb668192aec2a80',
    messagingSenderId: '309325071712',
    projectId: 'primekeyfinance-474f2',
    authDomain: 'primekeyfinance-474f2.firebaseapp.com',
    storageBucket: 'primekeyfinance-474f2.firebasestorage.app',
  );
}
